language: java

sudo: false

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "xi036bV33rqcUZI28oOdlkafNaeIcyyNE4bxStbJBuI5Uxtz0Ks0oOJj8uU2WgjRN3IyxUJW+Jgev2CXfk0SlL5NJGKi0QLpVeIEEKgQDJXvyNwRFORclRKNQHRaRuOYeklsZD0pODBwYvIvF80xiQKMoeZ2r15GhNwKdtngi5o="

addons:
  coverity_scan:
    project:
      name: "senbox-org/snap-engine"
      description: "Build submitted via Travis CI"
    notification_email: stb-coverity@thor.si.c-s.fr
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

before_install:
  # Work around discontinued nexus.codehaus.org (see https://github.com/travis-ci/travis-ci/issues/4629)
  # For building, everything is available in nexus.senbox.net, which is stored in pom.xml,
  #Â so we just completely remove the default repositories settings
  - cat ~/.m2/settings.xml
  - sed -i -n '/<repositories>/{p; :a; N; /<\/repositories>/!ba; s/.*\n//}; p' ~/.m2/settings.xml
  - cat ~/.m2/settings.xml

